default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: blogappli_development

test:
  <<: *default
  database: blogappli_test

production:
  <<: *default
  database: blogappli_production
  username: blogappli
  password: <%= ENV['BLOGAPPLI_DATABASE_PASSWORD'] %>
